// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenNetLinkApp.Data.SGSettings;

namespace OpenNetLinkApp.Migrations.SGSettingData
{
    [DbContext(typeof(SGSettingDataContext))]
    [Migration("20200915091510_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("OpenNetLinkApp.Models.SGSettings.SGSettingData", b =>
                {
                    b.Property<int>("GROUPID")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Sqlite:Autoincrement", false);

                    b.Property<string>("APPRLINE")
                        .HasColumnType("varchar(2048)");

                    b.Property<int>("AUTOLOGINING")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DELAYDISPLAYPW")
                        .HasColumnType("TEXT");

                    b.Property<string>("UID")
                        .HasColumnType("varchar(128)");

                    b.Property<string>("UPW")
                        .HasColumnType("varchar(128)");

                    b.HasKey("GROUPID")
                        .HasName("PK_T_SG_SETTING_DATA_GROUPID");

                    b.ToTable("T_SG_SETTING_DATA");
                });
#pragma warning restore 612, 618
        }
    }
}
