// AddFileRM.idl : AddFileRM의 IDL 소스입니다.
//

// 이 파일은 MIDL 도구에 의해 처리되어
// 형식 라이브러리(AddFileRM.tlb) 및 마샬링 코드가 생성됩니다.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(ADBCAB4D-5F9D-44DE-B38B-C81D2C2B3D68),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IAddFileRM : IDispatch{
};
[
	uuid(C3ACC193-04FA-4B01-9349-5548935EC06A),
	version(1.0),
]
library AddFileRMLib
{
	importlib("stdole2.tlb");
	[
		uuid(B32FD04C-6961-42EA-9F11-0340B40CF529)
	]
	coclass AddFileRM
	{
		[default] interface IAddFileRM;
	};
};

