language: csharp
dotnet: 3.1.402
dist: trusty
mono: none
matrix:
  include:
    - os: linux
branches:
  only:
    - github/management
script:
  - cd src/OpenNetLinkApp
  - dotnet restore
  - dotnet build
