language: csharp
dotnet: 3.1.402
matrix:
  include:
    - os: linux
branches:
  only:
    - github/management
script:
  - cd src/OpenNetLinkApp
  - dotnet restore
  - dotnet build
#after_success:
#  - curl --ftp-create-dirs -T build.zip -u ${travis_ftp_user}:${travis_ftp_pass} ftp://$travis_ftp_host/build_v${version_number}_b${build_number}.zip
#  - curl --data "version=${version_number}&build=${build_number}&update_key=${travis_update_key}" ${travis_update_url}
