// AddFileRM.idl : AddFileRM의 IDL 소스입니다.
//

// 이 파일은 MIDL 도구에 의해 처리되어
// 형식 라이브러리(AddFileRM.tlb) 및 마샬링 코드가 생성됩니다.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(4D21043D-E430-490D-84C8-8B81461FF4DC),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IAddFileRM : IDispatch{
};
[
	uuid(4E52A46A-72D9-4EA2-A22E-68FB5B108266),
	version(1.0),
]
library AddFileRMLib
{
	importlib("stdole2.tlb");
	[
		uuid(77265A4A-E102-431F-9F6F-6050237F817C)		
	]
	coclass AddFileRM
	{
		[default] interface IAddFileRM;
	};
};

