// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenNetLinkApp.Data.SGNotify;

namespace OpenNetLinkApp.Migrations
{
    [DbContext(typeof(SGNotifyContext))]
    partial class SGNotifyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("OpenNetLinkApp.Models.SGNotify.SGAlarmData", b =>
                {
                    b.Property<long>("AlarmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Head")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("IconImage")
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Path")
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("Time")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("AlarmId", "GroupId")
                        .HasName("PK_T_SG_ALARM_ALARMID_GROUPID");

                    b.ToTable("T_SG_ALARM");
                });

            modelBuilder.Entity("OpenNetLinkApp.Models.SGNotify.SGNotiData", b =>
                {
                    b.Property<long>("NotiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Head")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("IconImage")
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Path")
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("Time")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("NotiId", "GroupId")
                        .HasName("PK_T_SG_NOTI_NOTIID_GROUPID");

                    b.ToTable("T_SG_NOTI");
                });
#pragma warning restore 612, 618
        }
    }
}
