// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenNetLinkApp.Data.SGSettings;

namespace OpenNetLinkApp.Migrations.SGLoginData
{
    [DbContext(typeof(SGLoginDataContext))]
    partial class SGLoginDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("OpenNetLinkApp.Models.SGSettings.SGLoginData", b =>
                {
                    b.Property<int>("GROUPID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("APPRLINE")
                        .HasColumnType("varchar(2048)");

                    b.Property<int>("AUTOLOGINING")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DELAYDISPLAYPW")
                        .HasColumnType("TEXT");

                    b.Property<string>("UID")
                        .HasColumnType("varchar(128)");

                    b.Property<string>("UPW")
                        .HasColumnType("varchar(128)");

                    b.HasKey("GROUPID")
                        .HasName("PK_T_SG_LOGIN_DATA_GROUPID");

                    b.ToTable("T_SG_LOGIN_DATA");
                });
#pragma warning restore 612, 618
        }
    }
}
