// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenNetLinkApp.Data.SGNotify;

namespace OpenNetLinkApp.Migrations.SGNotify
{
    [DbContext(typeof(SGNotifyContext))]
    [Migration("20201021055559_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("OpenNetLinkApp.Models.SGNotify.SGAlarmData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Head")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("IconImage")
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Path")
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("Time")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now','localtime')");

                    b.Property<string>("UserSeq")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK_T_SG_ALARM_ID");

                    b.ToTable("T_SG_ALARM");
                });

            modelBuilder.Entity("OpenNetLinkApp.Models.SGNotify.SGNotiData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("varchar(4096)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Head")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.Property<string>("IconImage")
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Path")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Seq")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Time")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now','localtime')");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserSeq")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK_T_SG_NOTI_ID");

                    b.ToTable("T_SG_NOTI");
                });
#pragma warning restore 612, 618
        }
    }
}
